// Objects feature exports
export { useObjectsStore, generateObjectName } from './lib/objectsStore';
export { useSelectionStore } from './lib/selectionStore';
export { useUIPreferencesStore } from './lib/uiPreferencesStore';
export { firestore as db, rtdb, getFirestore, getRTDB } from '@/shared/services/firebase';
export { Rectangle } from './components/Rectangle';
export { Circle } from './components/Circle';
export { ObjectRenderer } from './components/ObjectRenderer';
export { ShapePreview } from './components/ShapePreview';
export { ContextMenu } from './components/ContextMenu';
export { PropertiesPanel } from './components/PropertiesPanel';
export { RightSidebar } from './components/RightSidebar';
export { SidebarPanel } from './components/SidebarPanel';
export { LayersPlaceholder } from './components/LayersPlaceholder';
export { LayerPanel } from './components/LayerPanel';
export { LayerItem } from './components/LayerItem';
export { LayerThumbnail } from './components/LayerThumbnail';
export { useObjects } from './hooks/useObjects';
export * from './services/objectsService';
export * from './types';
